### ISSUE TITLE
Description du dépôt

### ISSUE THREAD

**Issue by ocean-sicard-baux** [IUTInfoMontp-M2103/Ressources#1]
Bonjour, il y a une petite faute à « transparents », vous avez écrit transapents.

**Comment by MathieuSoysal** [comment]
Pour faciliter la maintenance, je te conseille de directement proposer un pull request ;)

**Comment by MathieuSoysal** [comment]
> 
> 
> Bonjour, il y a une petite faute à « transparents », vous avez écrit transapents.

Salut Ocean,
Pour faciliter la maintenance du professeur, je pense qu'il serait mieux si tu donnes plus de précisions sur l'endroit où il y a la faute.
Ou même si tu arrives à modifier un PDF de directement faire un pull-request.

**Comment by ocean-sicard-baux** [comment]
C'est dans la description du dépôt, comme j'ai écrit dans le titre. Voici une capture d'écran <img src="https://i.ibb.co/WGwDcTV/Screenshot-20200321-160618-Browser-1.png" width="200">
Je ne peux pas faire de pull-request, puisque c'est considéré comme un paramètres du projet donc il faut avoir les permissions

**Comment by MathieuSoysal** [comment]
![Mr.valicov](https://media.giphy.com/media/l0NwGpoOVLTAyUJSo/giphy.gif)
@pvalicov

**Comment by pvalicov** [comment]
Je viens de faire la modification. Merci pour l'info !
